version: '3.8'

services:
  mariadb:
    image: mariadb:10.3
    container_name: my-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mmbdev
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "4043:3306"  # Map host port 4040 to container port 3306
